from pydantic import BaseModel, Field
from typing import Optional
from sqlalchemy import create_engine
from sqlalchemy import text
from os import environ


class AuroraLogging(BaseModel):
    def log_to_database(self):
        SQL_HOST = environ.get("SQL_HOST", "localhost")
        SQL_USER = environ.get("SQL_USER", "zero")
        SQL_PASS = environ.get("SQL_PASS", "zero")
        mysql_write_engine = create_engine(f"mysql+pymysql://" + SQL_USER + ":zero@" + SQL_HOST + "/aurora")

        """
        Class for logging Aurora AI agent queries and results.
    
        Attributes:
            user_prompt: The natural language question asked by the user
            generated_query: The SQL query generated by the AI
            num_results: Number of results returned by the query
            user_feedback: Whether the user found the answer reasonable (True/False)
            results_returned_fl: Flag indicating if results were successfully returned
        """
        user_prompt: str = Field(description="The natural language question asked by the user")
        generated_query: str = Field(description="The SQL query generated by the AI")
        num_results: int = Field(description="Number of results returned by the query", default=0)
        user_feedback: Optional[bool] = Field(description="Whether the user found the answer reasonable", default=None)
        results_returned_fl: bool = Field(description="Flag indicating if results were successfully returned",
                                          default=False)

        # Log to database
        try:
            if user_feedback == '' or user_feedback is None:
                user_feedback = False
            with mysql_write_engine.connect() as log_conn:
                log_query = text("""
                                 INSERT INTO prompt_logs (user_prompt, generated_query, num_results,
                                                          user_feedback, created_at, results_returned_fl)
                                 VALUES (:question, :query, :num_results, :user_feedback, NOW(),
                                         :results_returned_fl)
                                 """)
                log_conn.execute(log_query, {
                    "question": user_prompt,
                    "query": generated_query,
                    "num_results": num_results,
                    "user_feedback": user_feedback,
                    "results_returned_fl": results_returned_fl
                })
                log_conn.commit()
            print("No feedback provided - recorded as negative feedback.")
        except Exception as log_error:
            print(f"Failed to log feedback: {log_error}")